const FACILITY_NAMES=["Bar","Main Stage","VIP","Private Dance Area","DJ Booth","Dressing Room","Parking Lot"];
const CAPACITY={1:2,2:3,3:4,4:5,5:6};
const SIGNING_FEE=1000;
const ASSETS={
  buildings:{1:"assets/buildings/neds-naughtiest-building-level-1.jpeg"},
  performers:{
    raven:"assets/performers/raven.jpeg",
    bambi:"assets/performers/bambi.jpeg",
    candy:"assets/performers/candy.jpeg",
    cherry:"assets/performers/cherry.jpeg",
    zella:"assets/performers/zella.jpeg",
    dallas:"assets/performers/dallas.jpeg"
  }
};
const PERFORMER_POOL=[
  {id:"raven",name:"Raven",concept:"Brunette bunny"},
  {id:"bambi",name:"Bambi",concept:"Blonde firefighter"},
  {id:"candy",name:"Candy",concept:"Blonde police officer"},
  {id:"cherry",name:"Cherry",concept:"Redheaded cheerleader"},
  {id:"zella",name:"Zella",concept:"Blonde schoolgirl"},
  {id:"dallas",name:"Dallas",concept:"Brunette cowgirl"}
];
function contractFor(performer){return {...performer,rank:"F",weeklyCost:200,weeksRemaining:26,trainingWeeks:0,revenueMultiplier:1}}
const state={week:1,cash:10000,buildingLevel:1,facilities:Object.fromEntries(FACILITY_NAMES.map(n=>[n,1])),performers:[contractFor(PERFORMER_POOL.find(p=>p.id==="zella"))],baseGross:1500};
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
function facilityUpgradeCost(level){return 1000*Math.pow(2,level-1)}
function buildingUpgradeCost(level){return 2000*Math.pow(2,level-1)}
function revenueBonus(){return Object.values(state.facilities).reduce((sum,l)=>sum+(l-1)*.05,0)}
function activePerformers(){return state.performers.filter(p=>p.trainingWeeks===0&&p.weeksRemaining>0)}
function rosterCount(){return state.performers.filter(p=>p.weeksRemaining>0).length}
function hasCapacity(){return rosterCount()<CAPACITY[state.buildingLevel]}
function grossRevenue(){const active=activePerformers();if(!active.length)return 0;const performerFactor=active.reduce((s,p)=>s+p.revenueMultiplier,0);return Math.round(state.baseGross*performerFactor*(1+revenueBonus()))}
function expenses(){const performerCosts=state.performers.filter(p=>p.weeksRemaining>0).reduce((s,p)=>s+p.weeklyCost,0);return {performers:performerCosts,tax:100,operations:500,advertising:100,sheriff:100}}
function netRevenue(){const e=expenses();return grossRevenue()-Object.values(e).reduce((a,b)=>a+b,0)}
function canUpgradeBuilding(){if(state.buildingLevel>=5)return false;return Object.values(state.facilities).every(l=>l>state.buildingLevel)}
function imageOrPlaceholder(src,alt,label,small,className){return `<div class="${className} art-frame"><img src="${src}" alt="${alt}" onerror="this.parentElement.classList.add('missing-art')" /><span>${label}</span><small>${small}</small></div>`}
function renderFacilities(){const root=document.querySelector("#facilities");root.innerHTML="";FACILITY_NAMES.forEach(name=>{const level=state.facilities[name],cost=facilityUpgradeCost(level),maxed=level>=5,locked=level>state.buildingLevel;const el=document.createElement("article");el.className="facility";el.innerHTML=`<p class="eyebrow">FACILITY</p><h3>${name}</h3><div class="level">Level ${level}</div><p class="muted">Revenue bonus: +${(level-1)*5}%</p><button ${maxed||locked||state.cash<cost?"disabled":""}>${maxed?"Max Level":locked?"Building upgrade required":`Upgrade — ${money(cost)}`}</button>`;el.querySelector("button").onclick=()=>upgradeFacility(name);root.appendChild(el)})}
function renderPerformers(){const root=document.querySelector("#performers");root.innerHTML="";state.performers.forEach(p=>{const el=document.createElement("article");el.className="performer";el.innerHTML=`${imageOrPlaceholder(ASSETS.performers[p.id],`${p.name} portrait`,p.name.toUpperCase(),"Portrait coming soon","portrait")}<p class="eyebrow">PERFORMER</p><h3>${p.name}</h3><dl><dt>Rank</dt><dd>${p.rank}</dd><dt>Weekly cost</dt><dd>${money(p.weeklyCost)}</dd><dt>Contract</dt><dd>${p.weeksRemaining} weeks</dd><dt>Status</dt><dd>${p.trainingWeeks?`Training (${p.trainingWeeks}w)`:"Working"}</dd></dl><button ${p.trainingWeeks||p.weeksRemaining<=4||state.cash<5000?"disabled":""}>Train — $5,000</button>`;el.querySelector("button").onclick=()=>train(p.id);root.appendChild(el)})}
function renderRecruitment(){const root=document.querySelector("#recruitment");root.innerHTML="";const hired=new Set(state.performers.map(p=>p.id));const full=!hasCapacity();document.querySelector("#market-status").textContent=full?`Club at capacity: ${rosterCount()}/${CAPACITY[state.buildingLevel]} performer slots filled.`:`Open slots: ${CAPACITY[state.buildingLevel]-rosterCount()}. Signing fee: ${money(SIGNING_FEE)}.`;PERFORMER_POOL.filter(p=>!hired.has(p.id)).forEach(p=>{const disabled=full||state.cash<SIGNING_FEE;const el=document.createElement("article");el.className="performer recruit";el.innerHTML=`${imageOrPlaceholder(ASSETS.performers[p.id],`${p.name} portrait`,p.name.toUpperCase(),"Portrait coming soon","portrait")}<p class="eyebrow">AVAILABLE CONTRACT</p><h3>${p.name}</h3><p class="muted">${p.concept}</p><dl><dt>Rank</dt><dd>F</dd><dt>Weekly cost</dt><dd>${money(200)}</dd><dt>Contract</dt><dd>Fresh 26 weeks</dd><dt>Signing fee</dt><dd>${money(SIGNING_FEE)}</dd></dl><button ${disabled?"disabled":""}>${full?"Club at capacity":state.cash<SIGNING_FEE?"Need cash":`Hire — ${money(SIGNING_FEE)}`}</button>`;el.querySelector("button").onclick=()=>hire(p.id);root.appendChild(el)})}
function renderLedger(){const e=expenses(),gross=grossRevenue(),net=netRevenue();document.querySelector("#ledger").innerHTML=`<div class="ledger-row"><span>Gross club revenue</span><strong class="positive">${money(gross)}</strong></div><div class="ledger-row"><span>Performer contracts</span><strong class="negative">-${money(e.performers)}</strong></div><div class="ledger-row"><span>Property tax</span><strong class="negative">-${money(e.tax)}</strong></div><div class="ledger-row"><span>Operations</span><strong class="negative">-${money(e.operations)}</strong></div><div class="ledger-row"><span>Advertising</span><strong class="negative">-${money(e.advertising)}</strong></div><div class="ledger-row"><span>Sheriff</span><strong class="negative">-${money(e.sheriff)}</strong></div><div class="ledger-row total"><span>Projected net</span><strong class="${net>=0?"positive":"negative"}">${money(net)}</strong></div>`}
function render(){document.querySelector("#week").textContent=state.week;document.querySelector("#cash").textContent=money(state.cash);document.querySelector("#building-level").textContent=state.buildingLevel;document.querySelector("#building-art").innerHTML=imageOrPlaceholder(ASSETS.buildings[state.buildingLevel]||"",`Ned's Naughtiest Building Level ${state.buildingLevel}`,`BUILDING LEVEL ${state.buildingLevel}`,"Artwork coming soon","building-art");document.querySelector("#capacity").textContent=CAPACITY[state.buildingLevel];document.querySelector("#capacity-used").textContent=rosterCount();const b=document.querySelector("#building-upgrade"),cost=buildingUpgradeCost(state.buildingLevel);b.textContent=state.buildingLevel>=5?"Building Maxed":`Upgrade Building — ${money(cost)}`;b.disabled=!canUpgradeBuilding()||state.cash<cost;document.querySelector("#building-requirement").textContent=state.buildingLevel>=5?"Ned's Naughties has reached Level 5.":`All facilities must reach Level ${state.buildingLevel+1} first.`;renderFacilities();renderPerformers();renderRecruitment();renderLedger()}
function upgradeFacility(name){const level=state.facilities[name],cost=facilityUpgradeCost(level);if(level>=5||level>state.buildingLevel||state.cash<cost)return;state.cash-=cost;state.facilities[name]++;setMessage(`${name} upgraded to Level ${state.facilities[name]}. Gross revenue bonus increased by 5%.`);render()}
function upgradeBuilding(){if(!canUpgradeBuilding())return;const cost=buildingUpgradeCost(state.buildingLevel);if(state.cash<cost)return;state.cash-=cost;state.buildingLevel++;setMessage(`Ned's Naughties is now Building Level ${state.buildingLevel}. Capacity increased to ${CAPACITY[state.buildingLevel]}.`);render()}
function hire(id){if(!hasCapacity()||state.cash<SIGNING_FEE)return;const performer=PERFORMER_POOL.find(p=>p.id===id);if(!performer||state.performers.some(p=>p.id===id&&p.weeksRemaining>0))return;state.cash-=SIGNING_FEE;state.performers.push(contractFor(performer));setMessage(`${performer.name} signed a fresh 26-week F-rank contract. Signing fee paid: ${money(SIGNING_FEE)}.`);render()}
function train(id){const p=state.performers.find(x=>x.id===id);if(!p||p.trainingWeeks||state.cash<5000)return;state.cash-=5000;p.trainingWeeks=4;setMessage(`${p.name} left for four weeks of dance and specialization training. Her contract clock keeps running.`);render()}
function finishTraining(p){const ranks=["F","E","D","C","B","A"],i=ranks.indexOf(p.rank);if(i<ranks.length-1)p.rank=ranks[i+1];p.revenueMultiplier*=1.25;const raise=[0,.05,.10,.15,.20,.25][Math.floor(Math.random()*6)];const old=p.weeklyCost;p.weeklyCost=Math.round(p.weeklyCost*(1+raise));return `${p.name} returned from training as Rank ${p.rank}. Revenue +25%. Weekly cost ${old===p.weeklyCost?`stays at ${money(old)}`:`rose from ${money(old)} to ${money(p.weeklyCost)}`}.`}
function advanceWeek(){const net=netRevenue();state.cash+=net;state.week++;let notices=[];state.performers.forEach(p=>{if(p.weeksRemaining>0)p.weeksRemaining--;if(p.trainingWeeks>0){p.trainingWeeks--;if(p.trainingWeeks===0)notices.push(finishTraining(p))}if(p.weeksRemaining===0)notices.push(`${p.name}'s 26-week contract has expired.`)});setMessage(notices.length?notices.join(" "):`Week ${state.week-1} closed at ${money(net)} net. Ted says, “Hell yeah, man. I think.”`);render()}
function setMessage(t){document.querySelector("#message").textContent=t}
document.querySelector("#advance-week").onclick=advanceWeek;document.querySelector("#building-upgrade").onclick=upgradeBuilding;render();
