const FACILITY_NAMES=["Bar","Main Stage","VIP","Private Dance Area","DJ Booth","Dressing Room","Parking Lot"];
const CAPACITY={1:2,2:3,3:4,4:5,5:6};
const BUILDING_EXPENSES={1:{tax:100,operations:500,advertising:100,sheriff:100},2:{tax:200,operations:750,advertising:150,sheriff:150},3:{tax:400,operations:1250,advertising:250,sheriff:250},4:{tax:750,operations:2000,advertising:400,sheriff:400},5:{tax:1250,operations:3500,advertising:750,sheriff:750}};
const SIGNING_FEE=1000;
const SAVE_KEY="neds-naughties-v01-save";
const ASSETS={buildings:{1:"assets/buildings/neds-naughtiest-building-level-1.jpeg"},performers:{raven:"assets/performers/raven.jpeg",bambi:"assets/performers/bambi.jpeg",candy:"assets/performers/candy.jpeg",cherry:"assets/performers/cherry.jpeg",zella:"assets/performers/zella.jpeg",dallas:"assets/performers/dallas.jpeg"}};
const PERFORMER_POOL=[{id:"raven",name:"Raven",concept:"Brunette bunny"},{id:"bambi",name:"Bambi",concept:"Blonde firefighter"},{id:"candy",name:"Candy",concept:"Blonde police officer"},{id:"cherry",name:"Cherry",concept:"Redheaded cheerleader"},{id:"zella",name:"Zella",concept:"Blonde schoolgirl"},{id:"dallas",name:"Dallas",concept:"Brunette cowgirl"}];
const byId=id=>PERFORMER_POOL.find(p=>p.id===id);
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const pct=(min,max)=>min+Math.random()*(max-min);
const rateWithPremium=(rate,min,max)=>Math.round(rate*(1+pct(min,max)));
const rateWithDiscount=(rate,min,max)=>Math.max(1,Math.round(rate*(1-pct(min,max))));
function contractFor(performer,overrides={}){return {...performer,rank:"F",weeklyCost:200,weeksRemaining:26,trainingWeeks:0,revenueMultiplier:1,trainingCompleted:0,history:[],renewalOffer:null,rehireOffer:null,...overrides}}
function newState(){return {week:1,cash:10000,buildingLevel:1,facilities:Object.fromEntries(FACILITY_NAMES.map(n=>[n,1])),performers:[contractFor(byId("zella"))],formerPerformers:[],baseGross:1500,selectedPerformerId:"zella",selectedSource:"active"}}
let state=loadState();
function normalizePerformer(p){const base=byId(p.id)||{id:p.id,name:p.name||"Unknown",concept:p.concept||"Former performer"};return contractFor(base,{...p,history:Array.isArray(p.history)?p.history:[],trainingCompleted:p.trainingCompleted||0,renewalOffer:p.renewalOffer||null,rehireOffer:p.rehireOffer||null})}
function migrate(raw){const fresh=newState();if(!raw||typeof raw!=="object")return fresh;return {...fresh,...raw,facilities:{...fresh.facilities,...raw.facilities},performers:(raw.performers||fresh.performers).map(normalizePerformer),formerPerformers:(raw.formerPerformers||[]).map(normalizePerformer),selectedPerformerId:raw.selectedPerformerId||"zella",selectedSource:raw.selectedSource||"active"}}
function loadState(){try{return migrate(JSON.parse(localStorage.getItem(SAVE_KEY)))}catch{return newState()}}
function saveState(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function commit(message){saveState();setMessage(message);render()}
function facilityUpgradeCost(level){return 1000*Math.pow(2,level-1)}
function buildingUpgradeCost(level){return 2000*Math.pow(2,level-1)}
function revenueBonus(){return Object.values(state.facilities).reduce((sum,l)=>sum+(l-1)*.05,0)}
function activePerformers(){return state.performers.filter(p=>p.trainingWeeks===0&&p.weeksRemaining>0)}
function rosterCount(){return state.performers.filter(p=>p.weeksRemaining>0).length}
function hasCapacity(){return rosterCount()<CAPACITY[state.buildingLevel]}
function grossRevenue(){const active=activePerformers();if(!active.length)return 0;const performerFactor=active.reduce((s,p)=>s+p.revenueMultiplier,0);return Math.round(state.baseGross*performerFactor*(1+revenueBonus()))}
function expenses(){const performerCosts=state.performers.filter(p=>p.weeksRemaining>0).reduce((s,p)=>s+p.weeklyCost,0);return {performers:performerCosts,...BUILDING_EXPENSES[state.buildingLevel]}}
function netRevenue(){const e=expenses();return grossRevenue()-Object.values(e).reduce((a,b)=>a+b,0)}
function canUpgradeBuilding(){if(state.buildingLevel>=5)return false;return Object.values(state.facilities).every(l=>l>state.buildingLevel)}
function imageOrPlaceholder(src,alt,label,small,className){return `<div class="${className} art-frame"><img src="${src}" alt="${alt}" onerror="this.parentElement.classList.add('missing-art')" /><span>${label}</span><small>${small}</small></div>`}
function statusFor(p){return p.weeksRemaining<=0?"Former":p.trainingWeeks?`Training (${p.trainingWeeks}w)`:"Working"}
function chooseProfile(id,source="active"){state.selectedPerformerId=id;state.selectedSource=source;saveState();render()}
function selectedPerformer(){return state.selectedSource==="former"?state.formerPerformers.find(p=>p.id===state.selectedPerformerId):state.performers.find(p=>p.id===state.selectedPerformerId)||state.performers[0]}
function moveFormer(p,reason){const previousRate=p.weeklyCost;const former={...p,weeksRemaining:0,trainingWeeks:0,lastWeeklyCost:previousRate,exitReason:reason,rehireOffer:null,renewalOffer:null,history:[...(p.history||[]),`${reason} at Week ${state.week}`]};state.formerPerformers=state.formerPerformers.filter(x=>x.id!==p.id).concat(former);state.performers=state.performers.filter(x=>x.id!==p.id);state.selectedPerformerId=former.id;state.selectedSource="former"}
function marketPerformers(){const activeIds=new Set(state.performers.map(p=>p.id));const formerIds=new Set(state.formerPerformers.map(p=>p.id));const fresh=PERFORMER_POOL.filter(p=>!activeIds.has(p.id)&&!formerIds.has(p.id)&&p.id!=="zella").map(p=>({kind:"fresh",performer:contractFor(p)}));const former=state.formerPerformers.filter(p=>!activeIds.has(p.id)).map(p=>({kind:"former",performer:p}));return [...fresh,...former]}
function hireRate(item){if(item.kind==="fresh")return 200;if(!item.performer.rehireOffer){const min=item.performer.exitReason==="fired"?.20:.10,max=item.performer.exitReason==="fired"?.35:.20;item.performer.rehireOffer=rateWithPremium(item.performer.lastWeeklyCost||item.performer.weeklyCost||200,min,max)}return item.performer.rehireOffer}
function renderFacilities(){const root=document.querySelector("#facilities");root.innerHTML="";FACILITY_NAMES.forEach(name=>{const level=state.facilities[name],cost=facilityUpgradeCost(level),maxed=level>=5,locked=level>state.buildingLevel;const el=document.createElement("article");el.className="facility";el.innerHTML=`<p class="eyebrow">FACILITY</p><h3>${name}</h3><div class="level">Level ${level}</div><p class="muted">Revenue bonus: +${(level-1)*5}%</p><button ${maxed||locked||state.cash<cost?"disabled":""}>${maxed?"Max Level":locked?"Building upgrade required":`Upgrade - ${money(cost)}`}</button>`;el.querySelector("button").onclick=()=>upgradeFacility(name);root.appendChild(el)})}
function rosterButton(p,source){const el=document.createElement("button");el.className="roster-item";el.innerHTML=`${imageOrPlaceholder(ASSETS.performers[p.id],`${p.name} portrait`,p.name.toUpperCase(),"Portrait coming soon","thumb")}<span><strong>${p.name}</strong><small>Rank ${p.rank} - ${statusFor(p)}</small></span>`;el.onclick=()=>chooseProfile(p.id,source);return el}
function renderRoster(){const working=document.querySelector("#working-performers"),training=document.querySelector("#training-performers"),former=document.querySelector("#former-performers");working.innerHTML="";training.innerHTML="";former.innerHTML="";state.performers.filter(p=>!p.trainingWeeks).forEach(p=>working.appendChild(rosterButton(p,"active")));state.performers.filter(p=>p.trainingWeeks).forEach(p=>training.appendChild(rosterButton(p,"active")));state.formerPerformers.forEach(p=>former.appendChild(rosterButton(p,"former")));if(!working.children.length)working.innerHTML=`<p class="muted empty">No working performers.</p>`;if(!training.children.length)training.innerHTML=`<p class="muted empty">No one is training.</p>`;if(!former.children.length)former.innerHTML=`<p class="muted empty">No former performers yet.</p>`}
function renderMarket(){const root=document.querySelector("#recruitment");root.innerHTML="";const items=marketPerformers();const full=!hasCapacity();document.querySelector("#market-status").textContent=full?`Club at capacity: ${rosterCount()}/${CAPACITY[state.buildingLevel]} performer slots filled.`:`Open slots: ${CAPACITY[state.buildingLevel]-rosterCount()}. Signing fee: ${money(SIGNING_FEE)}.`;items.forEach(item=>{const p=item.performer,rate=hireRate(item),disabled=full||state.cash<SIGNING_FEE;const el=document.createElement("article");el.className="performer recruit";el.innerHTML=`${imageOrPlaceholder(ASSETS.performers[p.id],`${p.name} portrait`,p.name.toUpperCase(),"Portrait coming soon","portrait")}<p class="eyebrow">${item.kind==="former"?"FORMER PERFORMER":"AVAILABLE CONTRACT"}</p><h3>${p.name}</h3><p class="muted">${p.concept}</p><dl><dt>Rank</dt><dd>${p.rank}</dd><dt>Weekly cost</dt><dd>${money(rate)}</dd><dt>Contract</dt><dd>Fresh 26 weeks</dd><dt>Signing fee</dt><dd>${money(SIGNING_FEE)}</dd></dl><button ${disabled?"disabled":""}>${full?"Club at capacity":state.cash<SIGNING_FEE?"Need cash":`Hire - ${money(SIGNING_FEE)}`}</button>`;el.querySelector("button").onclick=()=>hire(p.id,item.kind);root.appendChild(el)});if(!items.length)root.innerHTML=`<p class="muted empty">No available contracts.</p>`}
function renderProfile(){const p=selectedPerformer(),root=document.querySelector("#profile");if(!p){root.innerHTML=`<p class="muted empty">Select a performer.</p>`;return}const employed=state.performers.some(x=>x.id===p.id),canRenew=employed&&p.weeksRemaining>0;if(canRenew&&!p.renewalOffer)p.renewalOffer=rateWithDiscount(p.weeklyCost,.05,.10);const fireFee=employed?Math.round(p.weeklyCost*p.weeksRemaining*.5):0;root.innerHTML=`<div class="profile-grid">${imageOrPlaceholder(ASSETS.performers[p.id],`${p.name} portrait`,p.name.toUpperCase(),"Portrait coming soon","profile-art")}<div><p class="eyebrow">PERFORMER PROFILE</p><h2>${p.name}</h2><p class="muted">${p.concept}</p><dl class="profile-dl"><dt>Rank</dt><dd>${p.rank}</dd><dt>Weekly cost</dt><dd>${money(p.weeklyCost)}</dd><dt>Contract</dt><dd>${employed?`${p.weeksRemaining} weeks`:"Former"}</dd><dt>Status</dt><dd>${statusFor(p)}</dd><dt>Training completed</dt><dd>${p.trainingCompleted||0}</dd></dl><div class="profile-actions">${employed?`<button id="profile-train" ${p.trainingWeeks||p.weeksRemaining<=4||state.cash<5000?"disabled":""}>Train - $5,000</button><button id="profile-renew">Renew at ${money(p.renewalOffer)}</button><button id="profile-fire" ${state.cash<fireFee?"disabled":""}>Fire - ${money(fireFee)} fee</button>`:`<button id="profile-hire" ${!hasCapacity()||state.cash<SIGNING_FEE?"disabled":""}>Rehire - ${money(SIGNING_FEE)} fee</button>`}</div><p class="muted">${employed?`Early renewal resets ${p.name}'s contract to 26 weeks. Firing costs 50% of remaining contract value.`:`Former performer. Rehire creates a fresh 26-week contract.`}</p></div></div>`;if(employed){document.querySelector("#profile-train").onclick=()=>train(p.id);document.querySelector("#profile-renew").onclick=()=>renew(p.id);document.querySelector("#profile-fire").onclick=()=>firePerformer(p.id)}else document.querySelector("#profile-hire").onclick=()=>hire(p.id,"former")}
function renderLedger(){const e=expenses(),gross=grossRevenue(),net=netRevenue();document.querySelector("#ledger").innerHTML=`<div class="ledger-row"><span>Gross club revenue</span><strong class="positive">${money(gross)}</strong></div><div class="ledger-row"><span>Performer contracts</span><strong class="negative">-${money(e.performers)}</strong></div><div class="ledger-row"><span>Property tax</span><strong class="negative">-${money(e.tax)}</strong></div><div class="ledger-row"><span>Operations</span><strong class="negative">-${money(e.operations)}</strong></div><div class="ledger-row"><span>Advertising</span><strong class="negative">-${money(e.advertising)}</strong></div><div class="ledger-row"><span>Sheriff</span><strong class="negative">-${money(e.sheriff)}</strong></div><div class="ledger-row total"><span>Projected net</span><strong class="${net>=0?"positive":"negative"}">${money(net)}</strong></div>`}
function render(){document.querySelector("#week").textContent=state.week;document.querySelector("#cash").textContent=money(state.cash);document.querySelector("#building-level").textContent=state.buildingLevel;document.querySelector("#capacity").textContent=CAPACITY[state.buildingLevel];document.querySelector("#capacity-used").textContent=rosterCount();document.querySelector("#sticky-cash").textContent=money(state.cash);document.querySelector("#sticky-week").textContent=state.week;document.querySelector("#sticky-building").textContent=state.buildingLevel;document.querySelector("#sticky-capacity").textContent=`${rosterCount()}/${CAPACITY[state.buildingLevel]}`;document.querySelector("#building-art").innerHTML=imageOrPlaceholder(ASSETS.buildings[state.buildingLevel]||"",`Ned's Naughtiest Building Level ${state.buildingLevel}`,`BUILDING LEVEL ${state.buildingLevel}`,"Artwork coming soon","building-art");const b=document.querySelector("#building-upgrade"),cost=buildingUpgradeCost(state.buildingLevel);b.textContent=state.buildingLevel>=5?"Building Maxed":`Upgrade Building - ${money(cost)}`;b.disabled=!canUpgradeBuilding()||state.cash<cost;document.querySelector("#building-requirement").textContent=state.buildingLevel>=5?"Ned's Naughties has reached Level 5.":`All facilities must reach Level ${state.buildingLevel+1} first.`;renderFacilities();renderRoster();renderMarket();renderProfile();renderLedger();saveState()}
function upgradeFacility(name){const level=state.facilities[name],cost=facilityUpgradeCost(level);if(level>=5||level>state.buildingLevel||state.cash<cost)return;state.cash-=cost;state.facilities[name]++;commit(`${name} upgraded to Level ${state.facilities[name]}. Gross revenue bonus increased by 5%.`)}
function upgradeBuilding(){if(!canUpgradeBuilding())return;const cost=buildingUpgradeCost(state.buildingLevel);if(state.cash<cost)return;state.cash-=cost;state.buildingLevel++;commit(`Ned's Naughties is now Building Level ${state.buildingLevel}. Capacity increased to ${CAPACITY[state.buildingLevel]}.`)}
function hire(id,kind="fresh"){if(!hasCapacity()||state.cash<SIGNING_FEE)return;const active=state.performers.some(p=>p.id===id&&p.weeksRemaining>0);if(active)return;const former=state.formerPerformers.find(p=>p.id===id);const base=former||contractFor(byId(id));const item={kind:former?"former":kind,performer:base};const weeklyCost=hireRate(item);state.cash-=SIGNING_FEE;state.performers.push(contractFor(base,{...base,weeklyCost,weeksRemaining:26,trainingWeeks:0,renewalOffer:null,rehireOffer:null}));state.formerPerformers=state.formerPerformers.filter(p=>p.id!==id);state.selectedPerformerId=id;state.selectedSource="active";commit(`${base.name} signed a fresh 26-week contract. Signing fee paid: ${money(SIGNING_FEE)}.`)}
function train(id){const p=state.performers.find(x=>x.id===id);if(!p||p.trainingWeeks||state.cash<5000)return;state.cash-=5000;p.trainingWeeks=4;commit(`${p.name} left for four weeks of dance and specialization training. Her contract clock keeps running.`)}
function renew(id){const p=state.performers.find(x=>x.id===id);if(!p||p.weeksRemaining<=0)return;if(!p.renewalOffer)p.renewalOffer=rateWithDiscount(p.weeklyCost,.05,.10);p.weeklyCost=p.renewalOffer;p.weeksRemaining=26;p.renewalOffer=null;commit(`${p.name} renewed early at ${money(p.weeklyCost)}/week for a fresh 26 weeks.`)}
function firePerformer(id){const p=state.performers.find(x=>x.id===id);if(!p)return;const fee=Math.round(p.weeklyCost*p.weeksRemaining*.5);if(state.cash<fee)return;if(!confirm(`Terminate ${p.name}'s contract for ${money(fee)}?`))return;state.cash-=fee;moveFormer(p,"fired");commit(`${p.name}'s contract was terminated. Cancellation fee paid: ${money(fee)}.`)}
function finishTraining(p){const ranks=["F","E","D","C","B","A"],i=ranks.indexOf(p.rank);if(i<ranks.length-1)p.rank=ranks[i+1];p.revenueMultiplier*=1.25;p.trainingCompleted=(p.trainingCompleted||0)+1;p.renewalOffer=null;const raise=[0,.05,.10,.15,.20,.25][Math.floor(Math.random()*6)];const old=p.weeklyCost;p.weeklyCost=Math.round(p.weeklyCost*(1+raise));return `${p.name} returned from training as Rank ${p.rank}. Revenue +25%. Weekly cost ${old===p.weeklyCost?`stays at ${money(old)}`:`rose from ${money(old)} to ${money(p.weeklyCost)}`}.`}
function advanceWeek(){const net=netRevenue();state.cash+=net;state.week++;let notices=[];[...state.performers].forEach(p=>{if(p.weeksRemaining>0)p.weeksRemaining--;if(p.trainingWeeks>0){p.trainingWeeks--;if(p.trainingWeeks===0)notices.push(finishTraining(p))}if(p.weeksRemaining===0){notices.push(`${p.name}'s 26-week contract expired.`);moveFormer(p,"expired")}});commit(notices.length?notices.join(" "):`Week ${state.week-1} closed at ${money(net)} net. Ted says, "Hell yeah, man. I think."`)}
function newGame(){if(!confirm("Start a New Game? This will permanently erase your current Ned's Naughties save."))return;state=newState();saveState();setMessage("New game started. Ned's Naughties is back to Week 1.");render()}
function setMessage(t){document.querySelector("#message").textContent=t}
document.querySelector("#advance-week").onclick=advanceWeek;
document.querySelector("#building-upgrade").onclick=upgradeBuilding;
document.querySelector("#new-game").onclick=newGame;
render();
